version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: ecommerce-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: ecommerce_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecommerce-net

  backend:
    build: .
    container_name: ecommerce-fastapi
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - ecommerce-net

volumes:
  mysql_data:

networks:
  ecommerce-net:
    driver: bridge
