Inner Join: Students x Courses x Enrollments
('Anthony Smith', 'Educational psychologist', 'E')
('Michael Butler', 'Educational psychologist', 'A')
('Veronica Chan', 'Educational psychologist', 'B')
('Angela Lewis', 'Educational psychologist', 'E')
('Aaron Taylor', 'Educational psychologist', 'C')
('Thomas Carter', 'Educational psychologist', 'D')
('Nicole Taylor', 'Educational psychologist', 'C')
('Richard Fisher', 'Educational psychologist', 'B')
('Aaron Cummings', 'Scientist, audiological', 'E')
('David Montgomery', 'Scientist, audiological', 'C')
('Angela Lewis', 'Scientist, audiological', 'B')
('Stacey Thomas', 'Scientist, audiological', 'A')
('David Johns', 'Scientist, audiological', 'B')
('James Schroeder', 'Scientist, audiological', 'B')
('Travis Jenkins', 'Scientist, audiological', 'D')
('Janet Morgan', 'Scientist, audiological', 'C')
('Melvin Glenn', 'Scientist, audiological', 'D')
('Jeffery Lewis', 'Sport and exercise psychologist', 'C')
('Stephen Bryant', 'Sport and exercise psychologist', 'D')
('Anthony Smith', 'Sport and exercise psychologist', 'C')
('Michael Butler', 'Sport and exercise psychologist', 'A')
('Megan Jennings', 'Sport and exercise psychologist', 'C')
('Kelly Little', 'Sport and exercise psychologist', 'C')
('Robin Paul', 'Sport and exercise psychologist', 'D')
('David Johns', 'Sport and exercise psychologist', 'E')
('Emily Riley', 'Sport and exercise psychologist', 'C')
('Janet Morgan', 'Sport and exercise psychologist', 'C')
('Ronald Scott', 'Sport and exercise psychologist', 'A')
('Jon Lynch', 'Sport and exercise psychologist', 'C')
('Richard Fisher', 'Sport and exercise psychologist', 'A')
('Aaron Cummings', 'Doctor, hospital', 'A')
('Megan Jennings', 'Doctor, hospital', 'C')
('Veronica Chan', 'Doctor, hospital', 'C')
('Deanna Andrews', 'Doctor, hospital', 'E')
('Robin Paul', 'Doctor, hospital', 'D')
('Aaron Taylor', 'Doctor, hospital', 'E')
('James Schroeder', 'Doctor, hospital', 'C')
('Emily Riley', 'Doctor, hospital', 'E')
('Ronald Scott', 'Doctor, hospital', 'E')
('Jon Lynch', 'Doctor, hospital', 'E')
('Thomas Carter', 'Doctor, hospital', 'D')
('Adam Jackson', 'Doctor, hospital', 'E')
('Tracy Gonzalez', 'Doctor, hospital', 'A')
('Jeffery Lewis', "Politician's assistant", 'A')
('Stephen Bryant', "Politician's assistant", 'B')
('David Montgomery', "Politician's assistant", 'B')
('Deanna Andrews', "Politician's assistant", 'B')
('Kelly Little', "Politician's assistant", 'C')
('Stacey Thomas', "Politician's assistant", 'A')
('Travis Jenkins', "Politician's assistant", 'E')
('Melvin Glenn', "Politician's assistant", 'D')
('Nicole Taylor', "Politician's assistant", 'A')
('Adam Jackson', "Politician's assistant", 'B')
('Tracy Gonzalez', "Politician's assistant", 'A')


Inner Join: All courses with at least one student involved
('Doctor, hospital', 13)
('Scientist, audiological', 9)
("Politician's assistant", 11)
('Sport and exercise psychologist', 13)
('Educational psychologist', 8)


Left Join: Students and their Enrollments
('Aaron Cummings', 'A')
('Aaron Cummings', 'E')
('Jeffery Lewis', 'A')
('Jeffery Lewis', 'C')
('Stephen Bryant', 'B')
('Stephen Bryant', 'D')
('Anthony Smith', 'E')
('Anthony Smith', 'C')
('Michael Butler', 'A')
('Michael Butler', 'A')
('Megan Jennings', 'C')
('Megan Jennings', 'C')
('Veronica Chan', 'C')
('Veronica Chan', 'B')
('David Montgomery', 'C')
('David Montgomery', 'B')
('Angela Lewis', 'E')
('Angela Lewis', 'B')
('Deanna Andrews', 'B')
('Deanna Andrews', 'E')
('Kelly Little', 'C')
('Kelly Little', 'C')
('Robin Paul', 'D')
('Robin Paul', 'D')
('Stacey Thomas', 'A')
('Stacey Thomas', 'A')
('David Johns', 'B')
('David Johns', 'E')
('Aaron Taylor', 'E')
('Aaron Taylor', 'C')
('James Schroeder', 'B')
('James Schroeder', 'C')
('Travis Jenkins', 'D')
('Travis Jenkins', 'E')
('Emily Riley', 'C')
('Emily Riley', 'E')
('Janet Morgan', 'C')
('Janet Morgan', 'C')
('Ronald Scott', 'E')
('Ronald Scott', 'A')
('Jon Lynch', 'C')
('Jon Lynch', 'E')
('Melvin Glenn', 'D')
('Melvin Glenn', 'D')
('Thomas Carter', 'D')
('Thomas Carter', 'D')
('Nicole Taylor', 'C')
('Nicole Taylor', 'A')
('Adam Jackson', 'B')
('Adam Jackson', 'E')
('Richard Fisher', 'A')
('Richard Fisher', 'B')
('Tracy Gonzalez', 'A')
('Tracy Gonzalez', 'A')
('Maria Jackson', None)
('Mckenzie Greer', None)
('Amy Whitaker', None)


Left Join: Students enrolled in exactly zero or more than one course
('Aaron Cummings', 2)
('Jeffery Lewis', 2)
('Stephen Bryant', 2)
('Anthony Smith', 2)
('Michael Butler', 2)
('Megan Jennings', 2)
('Veronica Chan', 2)
('David Montgomery', 2)
('Angela Lewis', 2)
('Deanna Andrews', 2)
('Kelly Little', 2)
('Robin Paul', 2)
('Stacey Thomas', 2)
('David Johns', 2)
('Aaron Taylor', 2)
('James Schroeder', 2)
('Travis Jenkins', 2)
('Emily Riley', 2)
('Janet Morgan', 2)
('Ronald Scott', 2)
('Jon Lynch', 2)
('Melvin Glenn', 2)
('Thomas Carter', 2)
('Nicole Taylor', 2)
('Adam Jackson', 2)
('Richard Fisher', 2)
('Tracy Gonzalez', 2)
('Maria Jackson', 0)
('Mckenzie Greer', 0)
('Amy Whitaker', 0)


Right Join: Courses and number of students enrolled in them
('Doctor, hospital', 13)
('Scientist, audiological', 9)
("Politician's assistant", 11)
('Sport and exercise psychologist', 13)
('Educational psychologist', 8)

Right Join: Show all enrollments where courses are null
No results found.


Full Outer Join: All Students + All Enrollments
('Aaron Cummings', 'A')
('Aaron Cummings', 'E')
('Jeffery Lewis', 'A')
('Jeffery Lewis', 'C')
('Stephen Bryant', 'B')
('Stephen Bryant', 'D')
('Anthony Smith', 'E')
('Anthony Smith', 'C')
('Michael Butler', 'A')
('Megan Jennings', 'C')
('Veronica Chan', 'C')
('Veronica Chan', 'B')
('David Montgomery', 'C')
('David Montgomery', 'B')
('Angela Lewis', 'E')
('Angela Lewis', 'B')
('Deanna Andrews', 'B')
('Deanna Andrews', 'E')
('Kelly Little', 'C')
('Robin Paul', 'D')
('Stacey Thomas', 'A')
('David Johns', 'B')
('David Johns', 'E')
('Aaron Taylor', 'E')
('Aaron Taylor', 'C')
('James Schroeder', 'B')
('James Schroeder', 'C')
('Travis Jenkins', 'D')
('Travis Jenkins', 'E')
('Emily Riley', 'C')
('Emily Riley', 'E')
('Janet Morgan', 'C')
('Ronald Scott', 'E')
('Ronald Scott', 'A')
('Jon Lynch', 'C')
('Jon Lynch', 'E')
('Melvin Glenn', 'D')
('Thomas Carter', 'D')
('Nicole Taylor', 'C')
('Nicole Taylor', 'A')
('Adam Jackson', 'B')
('Adam Jackson', 'E')
('Richard Fisher', 'A')
('Richard Fisher', 'B')
('Tracy Gonzalez', 'A')
('Maria Jackson', None)
('Mckenzie Greer', None)
('Amy Whitaker', None)


Full Outer Join: All Courses + All Enrollments
('Educational psychologist', 'E')
('Educational psychologist', 'A')
('Educational psychologist', 'B')
('Educational psychologist', 'C')
('Educational psychologist', 'D')
('Scientist, audiological', 'E')
('Scientist, audiological', 'C')
('Scientist, audiological', 'B')
('Scientist, audiological', 'A')
('Scientist, audiological', 'D')
('Sport and exercise psychologist', 'C')
('Sport and exercise psychologist', 'D')
('Sport and exercise psychologist', 'A')
('Sport and exercise psychologist', 'E')
('Doctor, hospital', 'A')
('Doctor, hospital', 'C')
('Doctor, hospital', 'E')
('Doctor, hospital', 'D')
("Politician's assistant", 'A')
("Politician's assistant", 'B')
("Politician's assistant", 'C')
("Politician's assistant", 'E')
("Politician's assistant", 'D')
('Ranger/warden', None)
('Mechanical engineer', None)


Cross Join: All possible Student + Courses combination
('Aaron Cummings', 'Mechanical engineer')
('Aaron Cummings', 'Ranger/warden')
('Aaron Cummings', "Politician's assistant")
('Aaron Cummings', 'Doctor, hospital')
('Aaron Cummings', 'Sport and exercise psychologist')
('Aaron Cummings', 'Scientist, audiological')
('Aaron Cummings', 'Educational psychologist')
('Jeffery Lewis', 'Mechanical engineer')
('Jeffery Lewis', 'Ranger/warden')
('Jeffery Lewis', "Politician's assistant")
('Jeffery Lewis', 'Doctor, hospital')
('Jeffery Lewis', 'Sport and exercise psychologist')
('Jeffery Lewis', 'Scientist, audiological')
('Jeffery Lewis', 'Educational psychologist')
('Stephen Bryant', 'Mechanical engineer')
('Stephen Bryant', 'Ranger/warden')
('Stephen Bryant', "Politician's assistant")
('Stephen Bryant', 'Doctor, hospital')
('Stephen Bryant', 'Sport and exercise psychologist')
('Stephen Bryant', 'Scientist, audiological')
('Stephen Bryant', 'Educational psychologist')
('Anthony Smith', 'Mechanical engineer')
('Anthony Smith', 'Ranger/warden')
('Anthony Smith', "Politician's assistant")
('Anthony Smith', 'Doctor, hospital')
('Anthony Smith', 'Sport and exercise psychologist')
('Anthony Smith', 'Scientist, audiological')
('Anthony Smith', 'Educational psychologist')
('Michael Butler', 'Mechanical engineer')
('Michael Butler', 'Ranger/warden')
('Michael Butler', "Politician's assistant")
('Michael Butler', 'Doctor, hospital')
('Michael Butler', 'Sport and exercise psychologist')
('Michael Butler', 'Scientist, audiological')
('Michael Butler', 'Educational psychologist')
('Megan Jennings', 'Mechanical engineer')
('Megan Jennings', 'Ranger/warden')
('Megan Jennings', "Politician's assistant")
('Megan Jennings', 'Doctor, hospital')
('Megan Jennings', 'Sport and exercise psychologist')
('Megan Jennings', 'Scientist, audiological')
('Megan Jennings', 'Educational psychologist')
('Veronica Chan', 'Mechanical engineer')
('Veronica Chan', 'Ranger/warden')
('Veronica Chan', "Politician's assistant")
('Veronica Chan', 'Doctor, hospital')
('Veronica Chan', 'Sport and exercise psychologist')
('Veronica Chan', 'Scientist, audiological')
('Veronica Chan', 'Educational psychologist')
('David Montgomery', 'Mechanical engineer')
('David Montgomery', 'Ranger/warden')
('David Montgomery', "Politician's assistant")
('David Montgomery', 'Doctor, hospital')
('David Montgomery', 'Sport and exercise psychologist')
('David Montgomery', 'Scientist, audiological')
('David Montgomery', 'Educational psychologist')
('Angela Lewis', 'Mechanical engineer')
('Angela Lewis', 'Ranger/warden')
('Angela Lewis', "Politician's assistant")
('Angela Lewis', 'Doctor, hospital')
('Angela Lewis', 'Sport and exercise psychologist')
('Angela Lewis', 'Scientist, audiological')
('Angela Lewis', 'Educational psychologist')
('Deanna Andrews', 'Mechanical engineer')
('Deanna Andrews', 'Ranger/warden')
('Deanna Andrews', "Politician's assistant")
('Deanna Andrews', 'Doctor, hospital')
('Deanna Andrews', 'Sport and exercise psychologist')
('Deanna Andrews', 'Scientist, audiological')
('Deanna Andrews', 'Educational psychologist')
('Kelly Little', 'Mechanical engineer')
('Kelly Little', 'Ranger/warden')
('Kelly Little', "Politician's assistant")
('Kelly Little', 'Doctor, hospital')
('Kelly Little', 'Sport and exercise psychologist')
('Kelly Little', 'Scientist, audiological')
('Kelly Little', 'Educational psychologist')
('Robin Paul', 'Mechanical engineer')
('Robin Paul', 'Ranger/warden')
('Robin Paul', "Politician's assistant")
('Robin Paul', 'Doctor, hospital')
('Robin Paul', 'Sport and exercise psychologist')
('Robin Paul', 'Scientist, audiological')
('Robin Paul', 'Educational psychologist')
('Stacey Thomas', 'Mechanical engineer')
('Stacey Thomas', 'Ranger/warden')
('Stacey Thomas', "Politician's assistant")
('Stacey Thomas', 'Doctor, hospital')
('Stacey Thomas', 'Sport and exercise psychologist')
('Stacey Thomas', 'Scientist, audiological')
('Stacey Thomas', 'Educational psychologist')
('David Johns', 'Mechanical engineer')
('David Johns', 'Ranger/warden')
('David Johns', "Politician's assistant")
('David Johns', 'Doctor, hospital')
('David Johns', 'Sport and exercise psychologist')
('David Johns', 'Scientist, audiological')
('David Johns', 'Educational psychologist')
('Aaron Taylor', 'Mechanical engineer')
('Aaron Taylor', 'Ranger/warden')
('Aaron Taylor', "Politician's assistant")
('Aaron Taylor', 'Doctor, hospital')
('Aaron Taylor', 'Sport and exercise psychologist')
('Aaron Taylor', 'Scientist, audiological')
('Aaron Taylor', 'Educational psychologist')
('James Schroeder', 'Mechanical engineer')
('James Schroeder', 'Ranger/warden')
('James Schroeder', "Politician's assistant")
('James Schroeder', 'Doctor, hospital')
('James Schroeder', 'Sport and exercise psychologist')
('James Schroeder', 'Scientist, audiological')
('James Schroeder', 'Educational psychologist')
('Travis Jenkins', 'Mechanical engineer')
('Travis Jenkins', 'Ranger/warden')
('Travis Jenkins', "Politician's assistant")
('Travis Jenkins', 'Doctor, hospital')
('Travis Jenkins', 'Sport and exercise psychologist')
('Travis Jenkins', 'Scientist, audiological')
('Travis Jenkins', 'Educational psychologist')
('Emily Riley', 'Mechanical engineer')
('Emily Riley', 'Ranger/warden')
('Emily Riley', "Politician's assistant")
('Emily Riley', 'Doctor, hospital')
('Emily Riley', 'Sport and exercise psychologist')
('Emily Riley', 'Scientist, audiological')
('Emily Riley', 'Educational psychologist')
('Janet Morgan', 'Mechanical engineer')
('Janet Morgan', 'Ranger/warden')
('Janet Morgan', "Politician's assistant")
('Janet Morgan', 'Doctor, hospital')
('Janet Morgan', 'Sport and exercise psychologist')
('Janet Morgan', 'Scientist, audiological')
('Janet Morgan', 'Educational psychologist')
('Ronald Scott', 'Mechanical engineer')
('Ronald Scott', 'Ranger/warden')
('Ronald Scott', "Politician's assistant")
('Ronald Scott', 'Doctor, hospital')
('Ronald Scott', 'Sport and exercise psychologist')
('Ronald Scott', 'Scientist, audiological')
('Ronald Scott', 'Educational psychologist')
('Jon Lynch', 'Mechanical engineer')
('Jon Lynch', 'Ranger/warden')
('Jon Lynch', "Politician's assistant")
('Jon Lynch', 'Doctor, hospital')
('Jon Lynch', 'Sport and exercise psychologist')
('Jon Lynch', 'Scientist, audiological')
('Jon Lynch', 'Educational psychologist')
('Melvin Glenn', 'Mechanical engineer')
('Melvin Glenn', 'Ranger/warden')
('Melvin Glenn', "Politician's assistant")
('Melvin Glenn', 'Doctor, hospital')
('Melvin Glenn', 'Sport and exercise psychologist')
('Melvin Glenn', 'Scientist, audiological')
('Melvin Glenn', 'Educational psychologist')
('Thomas Carter', 'Mechanical engineer')
('Thomas Carter', 'Ranger/warden')
('Thomas Carter', "Politician's assistant")
('Thomas Carter', 'Doctor, hospital')
('Thomas Carter', 'Sport and exercise psychologist')
('Thomas Carter', 'Scientist, audiological')
('Thomas Carter', 'Educational psychologist')
('Nicole Taylor', 'Mechanical engineer')
('Nicole Taylor', 'Ranger/warden')
('Nicole Taylor', "Politician's assistant")
('Nicole Taylor', 'Doctor, hospital')
('Nicole Taylor', 'Sport and exercise psychologist')
('Nicole Taylor', 'Scientist, audiological')
('Nicole Taylor', 'Educational psychologist')
('Adam Jackson', 'Mechanical engineer')
('Adam Jackson', 'Ranger/warden')
('Adam Jackson', "Politician's assistant")
('Adam Jackson', 'Doctor, hospital')
('Adam Jackson', 'Sport and exercise psychologist')
('Adam Jackson', 'Scientist, audiological')
('Adam Jackson', 'Educational psychologist')
('Richard Fisher', 'Mechanical engineer')
('Richard Fisher', 'Ranger/warden')
('Richard Fisher', "Politician's assistant")
('Richard Fisher', 'Doctor, hospital')
('Richard Fisher', 'Sport and exercise psychologist')
('Richard Fisher', 'Scientist, audiological')
('Richard Fisher', 'Educational psychologist')
('Tracy Gonzalez', 'Mechanical engineer')
('Tracy Gonzalez', 'Ranger/warden')
('Tracy Gonzalez', "Politician's assistant")
('Tracy Gonzalez', 'Doctor, hospital')
('Tracy Gonzalez', 'Sport and exercise psychologist')
('Tracy Gonzalez', 'Scientist, audiological')
('Tracy Gonzalez', 'Educational psychologist')
('Maria Jackson', 'Mechanical engineer')
('Maria Jackson', 'Ranger/warden')
('Maria Jackson', "Politician's assistant")
('Maria Jackson', 'Doctor, hospital')
('Maria Jackson', 'Sport and exercise psychologist')
('Maria Jackson', 'Scientist, audiological')
('Maria Jackson', 'Educational psychologist')
('Mckenzie Greer', 'Mechanical engineer')
('Mckenzie Greer', 'Ranger/warden')
('Mckenzie Greer', "Politician's assistant")
('Mckenzie Greer', 'Doctor, hospital')
('Mckenzie Greer', 'Sport and exercise psychologist')
('Mckenzie Greer', 'Scientist, audiological')
('Mckenzie Greer', 'Educational psychologist')
('Amy Whitaker', 'Mechanical engineer')
('Amy Whitaker', 'Ranger/warden')
('Amy Whitaker', "Politician's assistant")
('Amy Whitaker', 'Doctor, hospital')
('Amy Whitaker', 'Sport and exercise psychologist')
('Amy Whitaker', 'Scientist, audiological')
('Amy Whitaker', 'Educational psychologist')


Cross Join: All possible Courses + Enrollments combination
('Mechanical engineer', 'A')
('Ranger/warden', 'A')
("Politician's assistant", 'A')
('Doctor, hospital', 'A')
('Sport and exercise psychologist', 'A')
('Scientist, audiological', 'A')
('Educational psychologist', 'A')
('Mechanical engineer', 'E')
('Ranger/warden', 'E')
("Politician's assistant", 'E')
('Doctor, hospital', 'E')
('Sport and exercise psychologist', 'E')
('Scientist, audiological', 'E')
('Educational psychologist', 'E')
('Mechanical engineer', 'A')
('Ranger/warden', 'A')
("Politician's assistant", 'A')
('Doctor, hospital', 'A')
('Sport and exercise psychologist', 'A')
('Scientist, audiological', 'A')
('Educational psychologist', 'A')
('Mechanical engineer', 'C')
('Ranger/warden', 'C')
("Politician's assistant", 'C')
('Doctor, hospital', 'C')
('Sport and exercise psychologist', 'C')
('Scientist, audiological', 'C')
('Educational psychologist', 'C')
('Mechanical engineer', 'B')
('Ranger/warden', 'B')
("Politician's assistant", 'B')
('Doctor, hospital', 'B')
('Sport and exercise psychologist', 'B')
('Scientist, audiological', 'B')
('Educational psychologist', 'B')
('Mechanical engineer', 'D')
('Ranger/warden', 'D')
("Politician's assistant", 'D')
('Doctor, hospital', 'D')
('Sport and exercise psychologist', 'D')
('Scientist, audiological', 'D')
('Educational psychologist', 'D')
('Mechanical engineer', 'E')
('Ranger/warden', 'E')
("Politician's assistant", 'E')
('Doctor, hospital', 'E')
('Sport and exercise psychologist', 'E')
('Scientist, audiological', 'E')
('Educational psychologist', 'E')
('Mechanical engineer', 'C')
('Ranger/warden', 'C')
("Politician's assistant", 'C')
('Doctor, hospital', 'C')
('Sport and exercise psychologist', 'C')
('Scientist, audiological', 'C')
('Educational psychologist', 'C')
('Mechanical engineer', 'A')
('Ranger/warden', 'A')
("Politician's assistant", 'A')
('Doctor, hospital', 'A')
('Sport and exercise psychologist', 'A')
('Scientist, audiological', 'A')
('Educational psychologist', 'A')
('Mechanical engineer', 'A')
('Ranger/warden', 'A')
("Politician's assistant", 'A')
('Doctor, hospital', 'A')
('Sport and exercise psychologist', 'A')
('Scientist, audiological', 'A')
('Educational psychologist', 'A')
('Mechanical engineer', 'C')
('Ranger/warden', 'C')
("Politician's assistant", 'C')
('Doctor, hospital', 'C')
('Sport and exercise psychologist', 'C')
('Scientist, audiological', 'C')
('Educational psychologist', 'C')
('Mechanical engineer', 'C')
('Ranger/warden', 'C')
("Politician's assistant", 'C')
('Doctor, hospital', 'C')
('Sport and exercise psychologist', 'C')
('Scientist, audiological', 'C')
('Educational psychologist', 'C')
('Mechanical engineer', 'C')
('Ranger/warden', 'C')
("Politician's assistant", 'C')
('Doctor, hospital', 'C')
('Sport and exercise psychologist', 'C')
('Scientist, audiological', 'C')
('Educational psychologist', 'C')
('Mechanical engineer', 'B')
('Ranger/warden', 'B')
("Politician's assistant", 'B')
('Doctor, hospital', 'B')
('Sport and exercise psychologist', 'B')
('Scientist, audiological', 'B')
('Educational psychologist', 'B')
('Mechanical engineer', 'C')
('Ranger/warden', 'C')
("Politician's assistant", 'C')
('Doctor, hospital', 'C')
('Sport and exercise psychologist', 'C')
('Scientist, audiological', 'C')
('Educational psychologist', 'C')
('Mechanical engineer', 'B')
('Ranger/warden', 'B')
("Politician's assistant", 'B')
('Doctor, hospital', 'B')
('Sport and exercise psychologist', 'B')
('Scientist, audiological', 'B')
('Educational psychologist', 'B')
('Mechanical engineer', 'E')
('Ranger/warden', 'E')
("Politician's assistant", 'E')
('Doctor, hospital', 'E')
('Sport and exercise psychologist', 'E')
('Scientist, audiological', 'E')
('Educational psychologist', 'E')
('Mechanical engineer', 'B')
('Ranger/warden', 'B')
("Politician's assistant", 'B')
('Doctor, hospital', 'B')
('Sport and exercise psychologist', 'B')
('Scientist, audiological', 'B')
('Educational psychologist', 'B')
('Mechanical engineer', 'B')
('Ranger/warden', 'B')
("Politician's assistant", 'B')
('Doctor, hospital', 'B')
('Sport and exercise psychologist', 'B')
('Scientist, audiological', 'B')
('Educational psychologist', 'B')
('Mechanical engineer', 'E')
('Ranger/warden', 'E')
("Politician's assistant", 'E')
('Doctor, hospital', 'E')
('Sport and exercise psychologist', 'E')
('Scientist, audiological', 'E')
('Educational psychologist', 'E')
('Mechanical engineer', 'C')
('Ranger/warden', 'C')
("Politician's assistant", 'C')
('Doctor, hospital', 'C')
('Sport and exercise psychologist', 'C')
('Scientist, audiological', 'C')
('Educational psychologist', 'C')
('Mechanical engineer', 'C')
('Ranger/warden', 'C')
("Politician's assistant", 'C')
('Doctor, hospital', 'C')
('Sport and exercise psychologist', 'C')
('Scientist, audiological', 'C')
('Educational psychologist', 'C')
('Mechanical engineer', 'D')
('Ranger/warden', 'D')
("Politician's assistant", 'D')
('Doctor, hospital', 'D')
('Sport and exercise psychologist', 'D')
('Scientist, audiological', 'D')
('Educational psychologist', 'D')
('Mechanical engineer', 'D')
('Ranger/warden', 'D')
("Politician's assistant", 'D')
('Doctor, hospital', 'D')
('Sport and exercise psychologist', 'D')
('Scientist, audiological', 'D')
('Educational psychologist', 'D')
('Mechanical engineer', 'A')
('Ranger/warden', 'A')
("Politician's assistant", 'A')
('Doctor, hospital', 'A')
('Sport and exercise psychologist', 'A')
('Scientist, audiological', 'A')
('Educational psychologist', 'A')
('Mechanical engineer', 'A')
('Ranger/warden', 'A')
("Politician's assistant", 'A')
('Doctor, hospital', 'A')
('Sport and exercise psychologist', 'A')
('Scientist, audiological', 'A')
('Educational psychologist', 'A')
('Mechanical engineer', 'B')
('Ranger/warden', 'B')
("Politician's assistant", 'B')
('Doctor, hospital', 'B')
('Sport and exercise psychologist', 'B')
('Scientist, audiological', 'B')
('Educational psychologist', 'B')
('Mechanical engineer', 'E')
('Ranger/warden', 'E')
("Politician's assistant", 'E')
('Doctor, hospital', 'E')
('Sport and exercise psychologist', 'E')
('Scientist, audiological', 'E')
('Educational psychologist', 'E')
('Mechanical engineer', 'E')
('Ranger/warden', 'E')
("Politician's assistant", 'E')
('Doctor, hospital', 'E')
('Sport and exercise psychologist', 'E')
('Scientist, audiological', 'E')
('Educational psychologist', 'E')
('Mechanical engineer', 'C')
('Ranger/warden', 'C')
("Politician's assistant", 'C')
('Doctor, hospital', 'C')
('Sport and exercise psychologist', 'C')
('Scientist, audiological', 'C')
('Educational psychologist', 'C')
('Mechanical engineer', 'B')
('Ranger/warden', 'B')
("Politician's assistant", 'B')
('Doctor, hospital', 'B')
('Sport and exercise psychologist', 'B')
('Scientist, audiological', 'B')
('Educational psychologist', 'B')
('Mechanical engineer', 'C')
('Ranger/warden', 'C')
("Politician's assistant", 'C')
('Doctor, hospital', 'C')
('Sport and exercise psychologist', 'C')
('Scientist, audiological', 'C')
('Educational psychologist', 'C')
('Mechanical engineer', 'D')
('Ranger/warden', 'D')
("Politician's assistant", 'D')
('Doctor, hospital', 'D')
('Sport and exercise psychologist', 'D')
('Scientist, audiological', 'D')
('Educational psychologist', 'D')
('Mechanical engineer', 'E')
('Ranger/warden', 'E')
("Politician's assistant", 'E')
('Doctor, hospital', 'E')
('Sport and exercise psychologist', 'E')
('Scientist, audiological', 'E')
('Educational psychologist', 'E')
('Mechanical engineer', 'C')
('Ranger/warden', 'C')
("Politician's assistant", 'C')
('Doctor, hospital', 'C')
('Sport and exercise psychologist', 'C')
('Scientist, audiological', 'C')
('Educational psychologist', 'C')
('Mechanical engineer', 'E')
('Ranger/warden', 'E')
("Politician's assistant", 'E')
('Doctor, hospital', 'E')
('Sport and exercise psychologist', 'E')
('Scientist, audiological', 'E')
('Educational psychologist', 'E')
('Mechanical engineer', 'C')
('Ranger/warden', 'C')
("Politician's assistant", 'C')
('Doctor, hospital', 'C')
('Sport and exercise psychologist', 'C')
('Scientist, audiological', 'C')
('Educational psychologist', 'C')
('Mechanical engineer', 'C')
('Ranger/warden', 'C')
("Politician's assistant", 'C')
('Doctor, hospital', 'C')
('Sport and exercise psychologist', 'C')
('Scientist, audiological', 'C')
('Educational psychologist', 'C')
('Mechanical engineer', 'E')
('Ranger/warden', 'E')
("Politician's assistant", 'E')
('Doctor, hospital', 'E')
('Sport and exercise psychologist', 'E')
('Scientist, audiological', 'E')
('Educational psychologist', 'E')
('Mechanical engineer', 'A')
('Ranger/warden', 'A')
("Politician's assistant", 'A')
('Doctor, hospital', 'A')
('Sport and exercise psychologist', 'A')
('Scientist, audiological', 'A')
('Educational psychologist', 'A')
('Mechanical engineer', 'C')
('Ranger/warden', 'C')
("Politician's assistant", 'C')
('Doctor, hospital', 'C')
('Sport and exercise psychologist', 'C')
('Scientist, audiological', 'C')
('Educational psychologist', 'C')
('Mechanical engineer', 'E')
('Ranger/warden', 'E')
("Politician's assistant", 'E')
('Doctor, hospital', 'E')
('Sport and exercise psychologist', 'E')
('Scientist, audiological', 'E')
('Educational psychologist', 'E')
('Mechanical engineer', 'D')
('Ranger/warden', 'D')
("Politician's assistant", 'D')
('Doctor, hospital', 'D')
('Sport and exercise psychologist', 'D')
('Scientist, audiological', 'D')
('Educational psychologist', 'D')
('Mechanical engineer', 'D')
('Ranger/warden', 'D')
("Politician's assistant", 'D')
('Doctor, hospital', 'D')
('Sport and exercise psychologist', 'D')
('Scientist, audiological', 'D')
('Educational psychologist', 'D')
('Mechanical engineer', 'D')
('Ranger/warden', 'D')
("Politician's assistant", 'D')
('Doctor, hospital', 'D')
('Sport and exercise psychologist', 'D')
('Scientist, audiological', 'D')
('Educational psychologist', 'D')
('Mechanical engineer', 'D')
('Ranger/warden', 'D')
("Politician's assistant", 'D')
('Doctor, hospital', 'D')
('Sport and exercise psychologist', 'D')
('Scientist, audiological', 'D')
('Educational psychologist', 'D')
('Mechanical engineer', 'C')
('Ranger/warden', 'C')
("Politician's assistant", 'C')
('Doctor, hospital', 'C')
('Sport and exercise psychologist', 'C')
('Scientist, audiological', 'C')
('Educational psychologist', 'C')
('Mechanical engineer', 'A')
('Ranger/warden', 'A')
("Politician's assistant", 'A')
('Doctor, hospital', 'A')
('Sport and exercise psychologist', 'A')
('Scientist, audiological', 'A')
('Educational psychologist', 'A')
('Mechanical engineer', 'B')
('Ranger/warden', 'B')
("Politician's assistant", 'B')
('Doctor, hospital', 'B')
('Sport and exercise psychologist', 'B')
('Scientist, audiological', 'B')
('Educational psychologist', 'B')
('Mechanical engineer', 'E')
('Ranger/warden', 'E')
("Politician's assistant", 'E')
('Doctor, hospital', 'E')
('Sport and exercise psychologist', 'E')
('Scientist, audiological', 'E')
('Educational psychologist', 'E')
('Mechanical engineer', 'A')
('Ranger/warden', 'A')
("Politician's assistant", 'A')
('Doctor, hospital', 'A')
('Sport and exercise psychologist', 'A')
('Scientist, audiological', 'A')
('Educational psychologist', 'A')
('Mechanical engineer', 'B')
('Ranger/warden', 'B')
("Politician's assistant", 'B')
('Doctor, hospital', 'B')
('Sport and exercise psychologist', 'B')
('Scientist, audiological', 'B')
('Educational psychologist', 'B')
('Mechanical engineer', 'A')
('Ranger/warden', 'A')
("Politician's assistant", 'A')
('Doctor, hospital', 'A')
('Sport and exercise psychologist', 'A')
('Scientist, audiological', 'A')
('Educational psychologist', 'A')
('Mechanical engineer', 'A')
('Ranger/warden', 'A')
("Politician's assistant", 'A')
('Doctor, hospital', 'A')
('Sport and exercise psychologist', 'A')
('Scientist, audiological', 'A')
('Educational psychologist', 'A')


Left Anti Join: All students who are not enrolled in any course
(28, 'Maria Jackson')
(29, 'Mckenzie Greer')
(30, 'Amy Whitaker')


Left Anti Join: All students who haven't received any grade
(28, 'Maria Jackson')
(29, 'Mckenzie Greer')
(30, 'Amy Whitaker')


Right Anti Join: Courses that have no students enrolled
(6, 'Ranger/warden')
(7, 'Mechanical engineer')


Right Anti Join: Enrollments with students id not in Students table
No results found.